### ISSUE TITLE
Imported PDFs have no subject

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook-reader.com#2]
All my books are stored in Calibre and saved in a single directory on Dropbox for import into KyBook3.

epubs, etc. are given a subject based on their tag in Calibre and can be sorted by subject in KyBook3.

PDFs do not have a subject in KyBook3, so cannot be sorted by subject. This happens when the PDF in Calibre has a tag and/or if it has a subject in its internal metadata.

**Comment by kolyvan** [comment]
PDF metadata subject is not equal to KyBook's subject.
PDF's subject is a like a summary/annotation in KyBook terms.
PDF metadata does not contain anything like a genre/tag/category (or a subject in KyBook terms).
So Calibre can't store a genre/tag/anything into PDF, there is no common place for such things.
And therefore KyBook can't import nonexistent genre/tag/etc from PDF file.

**Comment by kolyvan** [comment]
And note for future, this repo github.com/kolyvan/kybook-reader.com is not right place to adding  issues about KyBook application.

https://github.com/kolyvan/kybook - is a right repo for issues related to the application.
