### ISSUE TITLE
Please commit strings file for KyBook3 as you did for KyBook2

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook-reader.com#3]
There are a number of mistakes/poor English expressions in the English strings used in KyBook3.

Please could you commit the file here so we can improve them.

**Comment by kolyvan** [comment]
Thank You for offering help with localization.
Yes, I plan to make a repo like kybook2-localization with localization files for KyBook3. 
I will do it when the localization data will be more or less stable.
