### ISSUE TITLE
Copying or moving files says completed before finishing

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook-reader.com#4]
Version 0.3.1 (63)

1. Select File Browser
2. Select Dropbox
3. Select a folder
4. Select tick icon and select five files
5. Select Move
6. Select iPad
7. Select (Tap to switch Move/Copy)
8. Select Select a folder
9. Watch carefully. File count skips from 3 to 4/5. and says complete whilst files are still downloading.

**Comment by kolyvan** [comment]
Quite possible due to asynchronous nature of progress notification. Some glitches are unavoidable.
