### ISSUE TITLE
File Browser fails to sort files

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook-reader.com#5]
Version 0.3.1 (63)

1. Select File Browser
2. Select iPad
3. Select sort icon
4. by Date
5. Files remain sorted by Title

**Comment by kolyvan** [comment]
Yes, thank you for reporting this issue.
I fixed it in the beta release #65.

**Comment by kolyvan** [comment]
And note, the File Browser in KyBook 3 is an obsolete feature.
Most likely I will completely remove File Browser later.
The Bookshelf is the right tool for books management.
