### ISSUE TITLE
iPad view causes a crash, apparently refreshing book covers

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook-reader.com#6]

**Comment by karlic** [comment]
Version 0.3.1 (63)

1. Select iPad
2. Scroll down the list of books (sorted by subject)
3. The app crashes

**Comment by kolyvan** [comment]
Sorry, but I can't reproduce this crash.
Could you please provide more info.
At least which version of KyBook3 do you use?
How many books was the bookshelf at the time when crash occurred?
Which presentation layout was selected:  cards, covers, etc?

And please note, I do not have any crash report from Apple about your described crash related to Bookshelf. 
Perhaps do you disallows to share crash data with app developers?
Please check your device  settings -> Privacy -> Analytics 
 - toggle on Share iPhone Analytics
 - toggle on Share with App Developers

**Comment by karlic** [comment]
@kolyvan I have enabled analytics. Does that mean you will be sent them automatically? Or do I need to send them somehow.

**Comment by karlic** [comment]
This was happening every single time I scrolled down, but has now stopped, so I'll assumed it is now resolved and close this issue.
